echo ">>> Running macOS Suite..."
check "Has osxkeychain in .gitconfig" "grep -q 'osxkeychain' \$TMP_HOME/.gitconfig"
check "Brew commands in install script" "grep -q 'brew install' \$TMP_HOME/00_install_packages.sh"
check "fzf in brew install list" "grep -q 'brew install.*fzf' \$TMP_HOME/00_install_packages.sh"
check "Font installation skipped on macOS (custom script)" "grep -q 'Skipping font installation' \$TMP_HOME/after_install_fonts.sh"
